<a href="https://colab.research.google.com/github/wooihaw/k-youth-251101/blob/main/Lab_2/Lab_2a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lab 2a
#### The sinking of the RMS Titanic is one of the most infamous tragedy in history. In this hands-on, a machine learning system will be developed to predict which passengers survived the tragedy.

In [1]:
# Initialization
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
# Load libraries
import pandas as pd
from sklearn.model_selection import train_test_split as split, KFold, GridSearchCV
from sklearn.tree import DecisionTreeClassifier

# Load dataset from csv file
df1 = pd.read_csv('https://raw.githubusercontent.com/wooihaw/datasets/main/titanic.csv')

In [3]:
# Preview 10 random samples of the dataset
df1.sample(10)

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
338,339,1,3,"Dahl, Mr. Karl Edwart",male,45.0,0,0,7598,8.0500,NaN,S
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0000,NaN,S
735,736,0,3,"Williams, Mr. Leslie",male,28.5,0,0,54636,16.1000,NaN,S
733,734,0,2,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S
690,691,1,1,"Dick, Mr. Albert Adrian",male,31.0,1,0,17474,57.0000,B20,S
605,606,0,3,"Lindell, Mr. Edvard Bengtsson",male,36.0,1,0,349910,15.5500,NaN,S
196,197,0,3,"Mernagh, Mr. Robert",male,NaN,0,0,368703,7.7500,NaN,Q
106,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S
197,198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.0,0,1,4579,8.4042,NaN,S
198,199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,370370,7.7500,NaN,Q

In [4]:
# Statistical summary
df1.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

**To do:**
- Check the number of missing data for each column

In [5]:
df1.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

**To do:**
- Select only the columns 'Pclass', 'Gender', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived' and store them in df2
- Print first 5 rows of df2

In [6]:
cols = ['Pclass', 'Gender', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']
df2 = df1[cols]
df2.head()

   Pclass  Gender   Age  SibSp  Parch     Fare  Survived
0       3    male  22.0      1      0   7.2500         0
1       1  female  38.0      1      0  71.2833         1
2       3  female  26.0      0      0   7.9250         1
3       1  female  35.0      1      0  53.1000         1
4       3    male  35.0      0      0   8.0500         0

**To do:**
- Replace the missing data (imputation) in 'Age' column in df2 using the statistics (mean, median etc.)
- Check whether there is any more missing data

In [7]:
df2['Age'] = df2['Age'].fillna(df2['Age'].median())
df2.isna().sum()

Pclass      0
Gender      0
Age         0
SibSp       0
Parch       0
Fare        0
Survived    0
dtype: int64

**To do:**
- Use get_dummies() function from pandas to convert categorical features into one hot encoding and store the results in df3
- Print first 5 rows of df3

In [8]:
df3 = pd.get_dummies(df2, columns=['Gender'])
df3.head()

   Pclass   Age  SibSp  Parch     Fare  Survived  Gender_female  Gender_male
0       3  22.0      1      0   7.2500         0          False         True
1       1  38.0      1      0  71.2833         1           True        False
2       3  26.0      0      0   7.9250         1           True        False
3       1  35.0      1      0  53.1000         1           True        False
4       3  35.0      0      0   8.0500         0          False         True

Save the pre-processed data for later use

In [9]:
df3.to_csv('titanic_processed.csv', index=False)

**To do:**
- Store the features as variable X and targets as variable y
- Split the features and targets into training and testing sets (25% for testing)

In [10]:
X = df3.drop(columns=['Survived'])
y = df3['Survived']
X_train, X_test, y_train, y_test = split(X, y, test_size=0.25, random_state=42)

**To do:**
- Evaluate the performance of decision tree classifier on the training and testing sets (using the default hyperparameter values)

In [14]:
dtc1 = DecisionTreeClassifier(random_state=42).fit(X_train, y_train)
print(f'dtc1 train score: {dtc1.score(X_train, y_train):.3%}')
print(f'dtc1 test score: {dtc1.score(X_test, y_test):.3%}')

dtc1 train score: 98.054%
dtc1 test score: 74.888%

**To do:**
- Use grid search to fine tune the following hyperparameters
    * criterion ('gini' or 'entropy')
    * max_leaf_nodes (from 2 to 20)

In [15]:
params = {}
params['criterion'] = ['gini', 'entropy']
params['max_leaf_nodes'] = range(2, 21)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
grid = GridSearchCV(DecisionTreeClassifier(), params, cv=kf, n_jobs=-1)
grid.fit(X_train, y_train)
print(grid.best_params_)

{'criterion': 'entropy', 'max_leaf_nodes': 7}

**To do:**
- Train a decision tree classifier with the best set of hyperparameter values
- Evaluate the performance of the resulting classifier on the training and testing sets

In [16]:
dtc2 = DecisionTreeClassifier(**grid.best_params_, random_state=42).fit(X_train, y_train)
print(f'dtc2 train score: {dtc2.score(X_train, y_train):.3%}')
print(f'dtc2 test score: {dtc2.score(X_test, y_test):.3%}')

dtc2 train score: 83.234%
dtc2 test score: 80.269%