<a href="https://colab.research.google.com/github/wooihaw/k-youth-2603/blob/main/Lab_1/Lab_1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lab 1b
#### This lab explores the encoding of categorical data and data imputation

In [1]:
# Initialization
%matplotlib inline
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
# Load libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split as split
from sklearn.neighbors import KNeighborsClassifier

In [3]:
# Load dataset from csv file and show the first 5 rows of data
df = pd.read_csv("https://raw.githubusercontent.com/wooihaw/datasets/main/income.csv")

**To do**  
- Print the first 5 rows of data samples

In [4]:
df.head()

   Age Education Gender City  Income
0   54    Master      F    C    High
1   63    Master      F    C    High
2   32  Bachelor      f    B     Low
3    0  Bachelor      f    C  Medium
4   37  Bachelor      F    A     Low

**To do:**
- Check the number of rows and columns using the DataFrame's info() method

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        250 non-null    int64
 1   Education  250 non-null    object
 2   Gender     250 non-null    object
 3   City       250 non-null    object
 4   Income     250 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.9+ KB

**To do**  
- Print the number of duplicated rows

In [8]:
print(df.duplicated().sum())

38

**To do:**
- Remove duplicated rows if there are any

In [9]:
df = df.drop_duplicates()

**To do**  
- Check the number of remaining rows using the DataFrame's info()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 212 entries, 0 to 249
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        212 non-null    int64
 1   Education  212 non-null    object
 2   Gender     212 non-null    object
 3   City       212 non-null    object
 4   Income     212 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.9+ KB

**To do:**
- Check the number of missing values for each column using the DataFrame's isna().sum() method

In [11]:
df.isna().sum()

Age          0
Education    0
Gender       0
City         0
Income       0
dtype: int64

**To do:**
- Calculate descriptive statistics using the DataFrame's describe() method
- Identify any issue from the descriptive statistics

In [12]:
df.describe()

              Age
count  212.000000
mean    40.981132
std     12.042170
min      0.000000
25%     35.000000
50%     40.000000
75%     50.000000
max     65.000000

**To do:**
- Replace missing value (0) with NaN
- Check the number of missing values for each column using the DataFrame's isna().sum() method

In [13]:
df = df.replace({0:np.nan})
df.isna().sum()

Age          7
Education    0
Gender       0
City         0
Income       0
dtype: int64

**To do**  
- Print the first 5 rows of the resulting dataframe (df)

In [14]:
df.head()

    Age Education Gender City  Income
0  54.0    Master      F    C    High
1  63.0    Master      F    C    High
2  32.0  Bachelor      f    B     Low
3   NaN  Bachelor      f    C  Medium
4  37.0  Bachelor      F    A     Low

**To do:**
- Print unique values in the Education column.

In [15]:
df['Education'].unique()

array(['Master', 'Bachelor', 'Diploma', 'PhD'], dtype=object)

**To do:**
- Define mapping for ordinal data
- Encode ordinal data using map().
- Print the first 5 rows of the resulting dataframe (df).

In [16]:
edu_levels = {'Diploma':1, 'Bachelor':2, 'Master':3, 'PhD':4}
df['Education'] = df['Education'].map(edu_levels)
df.head()

    Age  Education Gender City  Income
0  54.0          3      F    C    High
1  63.0          3      F    C    High
2  32.0          2      f    B     Low
3   NaN          2      f    C  Medium
4  37.0          2      F    A     Low

**To do:**
- Use pd.get_dummies() to encode nominal data using one-hot encoding and store the resulting dataframe in df1.
- Print first 5 rows of df1 and verify that the resulting dataframe is correct.

In [17]:
df1 = pd.get_dummies(df, columns=['Gender', 'City'])
df1.head()

,Age,Education,Income,Gender_F,Gender_M,Gender_f,Gender_m,City_A,City_B,City_C
0,54.0,3,High,True,False,False,False,False,False,True
1,63.0,3,High,True,False,False,False,False,False,True
2,32.0,2,Low,False,False,True,False,False,True,False
3,NaN,2,Medium,False,False,True,False,False,False,True
4,37.0,2,Low,True,False,False,False,True,False,False

**To do:**
- Rectify the problem in the previous step.
- Use pd.get_dummies() to encode nominal data using one-hot encoding and store the resulting dataframe in df2.
- Print the first 5 rows of df2.

In [18]:
df['Gender'] = df['Gender'].str.upper()
df2 = pd.get_dummies(df, columns=['Gender', 'City'])
df2.head()

    Age  Education  Income  Gender_F  Gender_M  City_A  City_B  City_C
0  54.0          3    High      True     False   False   False    True
1  63.0          3    High      True     False   False   False    True
2  32.0          2     Low      True     False   False    True   False
3   NaN          2  Medium      True     False   False   False    True
4  37.0          2     Low      True     False    True   False   False

**To do:**
- Impute missing data with median value of the column
- Check the number of missing values for each column using the DataFrame's isna().sum() method

In [19]:
df2['Age'] = df2['Age'].fillna(df2['Age'].median())
df2.isna().sum()

Age          0
Education    0
Income       0
Gender_F     0
Gender_M     0
City_A       0
City_B       0
City_C       0
dtype: int64

**To do**  
- Seperate to feature (X) and target (y)
- Split to training (X_train, y_train) and testing (X_test, y_test) sets (25% for testing)

In [20]:
X = df2.drop(columns=['Income'])
y = df2['Income']
X_train, X_test, y_train, y_test = split(X, y, test_size=0.25, random_state=42)

Train and evaluate a k-Nearest Neighbors model

In [21]:
# Train and evaluate a knn model
knn = KNeighborsClassifier().fit(X_train, y_train)
print(f"knn accuracy: {knn.score(X_test, y_test):.2%}")

knn accuracy: 98.11%